### PR TITLE
Fix font when using polish language

### PR DESCRIPTION
**Pull request by szczuru**
Clone russian.ttf as polish.ttf to fix font when using polish language.

### CODE REVIEW

**Comment by 1upus** [comment]
You can add your translation to my original QL Installer repo. Now I'm working on custom font loading for specific language. If russian.ttf works fine to you with polish translation, please report me.
We don't need duplicate same files with other names, I'll just fix the code.

**Comment by 1upus** [comment]
@theheroGAC please say that your app is fork or mode, because you make 7 releases (last - 0.4) with any critical code changes but original QL Installer still have version 0.2 and now I'm working on some bigger that adding translations. So next release will be v0.3 and more functional that your v0.4.
Thx.

**Comment by theheroGAC** [comment]
sorry. update my file read me and thank you for your tool.@szczuru The original project is here https://github.com/1upus/QuickLaunch_installer_for_PSVita

**Comment by 1upus** [comment]
Thx. If you make some code changes you can just make pull request to merge code with original repo.

**Comment by theheroGAC** [comment]
Ok thank you 👍

**Pull request closed without merging**
